apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongo-restore-cron
  namespace: mongodb
spec:
  schedule: "0 3 * * *"  # Runs daily at 3 AM (change if needed)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongo-restore
            image: mongo:6.0
            command:
              - "/bin/sh"
              - "-c"
              - >
                echo "Starting MongoDB Restore...";
                MONGO_URI=$(printf "mongodb://%s:%s@mongodb.mongodb.svc.cluster.local:27017/admin?authSource=admin&authMechanism=SCRAM-SHA-1" "$MONGO_USERNAME" "$MONGO_PASSWORD");
                echo "Using MongoDB URI: $MONGO_URI";
                LATEST_BACKUP=$(ls -td /backup/* | head -1);
                echo "Latest Backup: $LATEST_BACKUP";
                LATEST_DB_DUMP="$LATEST_BACKUP";
                echo "Restoring from: $LATEST_DB_DUMP";
                mongorestore --uri="$MONGO_URI" --drop --dir="$LATEST_DB_DUMP" --nsInclude=admin.* &&
                echo "Restore completed at $(date)";
            env:
              - name: MONGO_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: mongodb-secret
                    key: username
              - name: MONGO_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mongodb-secret
                    key: password
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          restartPolicy: Never
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: mongodb-pvc