apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongo-backup-cron
  namespace: mongodb
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongo-backup
            image: mongo:6.0
            command:
              - "/bin/sh"
              - "-c"
              - >
                echo "Starting MongoDB Backup...";
                echo "MongoDB Username: $MONGO_USERNAME";
                echo "MongoDB Password: $MONGO_PASSWORD";
                MONGO_URI=$(printf "mongodb://%s:%s@mongodb.mongodb.svc.cluster.local:27017/admin?authSource=admin&authMechanism=SCRAM-SHA-1" "$MONGO_USERNAME" "$MONGO_PASSWORD");
                echo "Using MongoDB URI: $MONGO_URI";
                mongodump --uri="$MONGO_URI" --out "/backup/$(date +%F-%H%M%S)" &&
                echo "Backup completed at $(date)";
            env:
              - name: MONGO_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: mongodb-secret
                    key: username
              - name: MONGO_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mongodb-secret
                    key: password
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          restartPolicy: Never
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: mongo-backup-pvc