apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongo-backup-cron
  namespace: mongodb
spec:
  schedule: "0 2 * * *"  # Every day at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongo-backup
            image: mongo:6.0
            command:
              - "/bin/sh"
              - "-c"
              - >
                mongodump --host mongodb.mongodb.svc.cluster.local --db My_App --out /backup/$(date +%F-%H%M%S) &&
                echo "Backup completed at $(date)"
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          restartPolicy: Never
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: mongo-backup-pvc