apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-backup-pv
  namespace: mongodb
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/mongo-backups